-- SQL para recriar/ajustar a tabela cameras no Supabase
CREATE TABLE IF NOT EXISTS cameras (
  id bigint generated by default as identity primary key,
  loja_numero text not null,
  loja_nome text not null,
  cloud text,
  camera_id text,
  ddns text,
  usuario text,
  senha text,
  porta_servico text,
  porta_web text,
  tipo_conexao text check (tipo_conexao in ('cloud', 'id', 'ddns')) not null,
  status text check (status in ('online', 'offline', 'sem sinal')) not null,
  cidade text,
  estado text,
  owner text not null,
  created_at timestamp with time zone default now()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_cameras_owner ON cameras(owner);
CREATE INDEX IF NOT EXISTS idx_cameras_status ON cameras(status);
CREATE INDEX IF NOT EXISTS idx_cameras_loja_numero ON cameras(loja_numero);
