-- Patch para criar a tabela users sem sobrescrever dados existentes
CREATE TABLE IF NOT EXISTS users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  owner text, -- Nome do responsável
  role text check (role in ('ti', 'adm', 'prevencao')) not null,
  pode_criar_usuarios boolean default false,
  ativo boolean default true,
  created_at timestamp with time zone default now()
);
