-- Criação da tabela cameras no Supabase
CREATE TABLE cameras (
  id bigint generated by default as identity primary key,
  loja_numero text not null,
  loja_nome text not null,
  cloud text,
  camera_id text,
  ddns text,
  usuario text,
  senha text,
  porta_servico text,
  porta_web text,
  tipo_conexao text check (tipo_conexao in ('cloud', 'id', 'ddns')) not null,
  status text check (status in ('online', 'offline', 'sem sinal')) not null
);
