-- SCHEMA COMPLETO PARA ACCESSCAM (SUPABASE)
-- Tabela de usuários
CREATE TABLE IF NOT EXISTS users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  owner text, -- Nome do responsável
  role text check (role in ('ti', 'adm', 'prevencao')) not null,
  pode_criar_usuarios boolean default false,
  ativo boolean default true,
  created_at timestamp with time zone default now()
);

-- Inserts de exemplo para usuários
INSERT INTO users (username, password, owner, role, pode_criar_usuarios) VALUES
  ('ti', 'Ginseng#13', 'TI', 'ti', true),
  ('prevencao', 'Prev123', 'Prevenção', 'prevencao', false),
  ('admin', 'Admin#2025', 'Administrador', 'adm', true);

-- Tabela de câmeras
CREATE TABLE IF NOT EXISTS cameras (
  id bigint generated by default as identity primary key,
  loja_numero text not null,
  loja_nome text not null,
  cloud text,
  camera_id text,
  ddns text,
  usuario text,
  senha text,
  porta_servico text,
  porta_web text,
  tipo_conexao text check (tipo_conexao in ('cloud', 'id', 'ddns')) not null,
  status text check (status in ('online', 'offline', 'sem sinal')) not null,
  responsavel_id bigint references users(id) on delete set null,
  responsavel_nome text, -- redundância para exibição rápida
  created_at timestamp with time zone default now()
);

-- Exemplo de insert de câmera
INSERT INTO cameras (
  loja_numero, loja_nome, cloud, camera_id, ddns, usuario, senha, porta_servico, porta_web, tipo_conexao, status, responsavel_id, responsavel_nome
) VALUES (
  '3546', 'LJ BIG BOMPREÇO GRUTA (SAMS)', '4MAM4300787VR', null, null, 'admin', 'Ginseng#13', '37777', null, 'cloud', 'online', 1, 'TI'
);

-- Permissões e auditoria (opcional)
CREATE TABLE IF NOT EXISTS user_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  acao text not null,
  detalhes jsonb,
  created_at timestamp with time zone default now()
);

-- View para facilitar consultas de câmeras por responsável
CREATE OR REPLACE VIEW cameras_por_responsavel AS
SELECT c.*, u.username as responsavel_username, u.owner as responsavel_owner, u.role as responsavel_role
FROM cameras c
LEFT JOIN users u ON c.responsavel_id = u.id;

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_cameras_responsavel_id ON cameras(responsavel_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
